/**
 * Canonical Seed Data for Organization Admin (Smile Care Group - org-001)
 *
 * Provides rich, realistic mock data for all dashboard domain tables:
 * - Patients
 * - Leads
 * - Calls
 * - Tasks
 * - Payments & Revenue
 * - Organization Staff Users
 */

export const ORG_001_ID = 'org-001';
export const ORG_001_NAME = 'Smile Care Group';

// Canonical clinic branches of Smile Care Group
export const ORG_001_CLINICS = {
  DOWNTOWN: 'clinic-downtown',
  WEST: 'clinic-west',
  GULBERG: 'clinic-003',
  CLIFTON: 'clinic-004',
};

// ── 1. PATIENTS DATA ──────────────────────────────────────────────────────────
export const SMILE_CARE_PATIENTS = [
  {
    id: 'pat-001',
    fullName: 'Ahmed Al-Rashidi',
    name: 'Ahmed Al-Rashidi',
    phone: '+971-50-1234567',
    email: 'ahmed.rashidi@example.com',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    status: 'Active',
    dateOfBirth: '1988-04-12',
    gender: 'Male',
    medicalHistory: 'Hypertension, Penicillin allergy (severe). Prefers morning slots.',
    lastVisit: '2026-08-25',
    totalVisits: 6,
    treatment: 'Dental Implant',
    insuranceProvider: 'Bupa Dental Platinum',
  },
  {
    id: 'pat-002',
    fullName: 'Sara Johnson',
    name: 'Sara Johnson',
    phone: '+1-555-2345',
    email: 'sara.j@example.com',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    status: 'Active',
    dateOfBirth: '1995-09-18',
    gender: 'Female',
    medicalHistory: 'Enamel sensitivity. Routine prophylaxis & teeth whitening follow-up.',
    lastVisit: '2026-09-02',
    totalVisits: 3,
    treatment: 'Teeth Whitening',
    insuranceProvider: 'Cigna Global Health',
  },
  {
    id: 'pat-003',
    fullName: 'Mohammed Hassan',
    name: 'Mohammed Hassan',
    phone: '+966-55-9876543',
    email: 'moh.hassan@example.com',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    status: 'Active',
    dateOfBirth: '1979-11-30',
    gender: 'Male',
    medicalHistory: 'Type 2 Diabetes (controlled). Undergoing multi-canal root therapy.',
    lastVisit: '2026-08-28',
    totalVisits: 7,
    treatment: 'Root Canal',
    insuranceProvider: 'Tawuniya Gold',
  },
  {
    id: 'pat-004',
    fullName: 'Fatima Al-Zaidi',
    name: 'Fatima Al-Zaidi',
    phone: '+971-55-3456789',
    email: 'fatima.zaidi@example.com',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    status: 'Active',
    dateOfBirth: '2004-03-22',
    gender: 'Female',
    medicalHistory: 'Orthodontic bracket repair on upper premolar. Ceramic braces.',
    lastVisit: '2026-08-30',
    totalVisits: 9,
    treatment: 'Orthodontics',
    insuranceProvider: 'MetLife Comprehensive',
  },
  {
    id: 'pat-005',
    fullName: 'Khalid Mansour',
    name: 'Khalid Mansour',
    phone: '+966-50-7654321',
    email: 'khalid.m@example.com',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    status: 'Active',
    dateOfBirth: '1984-06-14',
    gender: 'Male',
    medicalHistory: 'Cosmetic porcelain veneer fitting scheduled (upper 6 units).',
    lastVisit: '2026-08-15',
    totalVisits: 4,
    treatment: 'Porcelain Veneers',
    insuranceProvider: 'Bupa Dental Gold',
  },
  {
    id: 'pat-006',
    fullName: 'Nour El-Masry',
    name: 'Nour El-Masry',
    phone: '+20-10-1234567',
    email: 'nour.elmasry@example.com',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    status: 'Pending',
    dateOfBirth: '2016-08-05',
    gender: 'Female',
    medicalHistory: 'Pediatric checkup and fissure sealants. Mild dental anxiety.',
    lastVisit: '2026-09-01',
    totalVisits: 1,
    treatment: 'Pediatric Dentistry',
    insuranceProvider: 'Self-Pay',
  },
  {
    id: 'pat-007',
    fullName: 'Rania Haddad',
    name: 'Rania Haddad',
    phone: '+961-70-9876543',
    email: 'rania.haddad@example.com',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    status: 'Active',
    dateOfBirth: '1991-12-03',
    gender: 'Female',
    medicalHistory: 'Clear aligners refinement scan. Excellent compliance record.',
    lastVisit: '2026-08-20',
    totalVisits: 5,
    treatment: 'Invisalign',
    insuranceProvider: 'Cigna Global Health',
  },
  {
    id: 'pat-008',
    fullName: 'Omar Tariq',
    name: 'Omar Tariq',
    phone: '+92-300-1234567',
    email: 'omar.tariq@example.com',
    clinicId: ORG_001_CLINICS.GULBERG,
    orgId: ORG_001_ID,
    status: 'Active',
    dateOfBirth: '1987-07-29',
    gender: 'Male',
    medicalHistory: 'Single molar implant post-op check. Tissue integration normal.',
    lastVisit: '2026-08-10',
    totalVisits: 4,
    treatment: 'Dental Implant',
    insuranceProvider: 'Jubilee Life Insurance',
  },
  {
    id: 'pat-009',
    fullName: 'Lina Khalil',
    name: 'Lina Khalil',
    phone: '+961-71-5432109',
    email: 'lina.khalil@example.com',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    status: 'Active',
    dateOfBirth: '1993-01-15',
    gender: 'Female',
    medicalHistory: 'Zirconia crown prep on lower right molar #30.',
    lastVisit: '2026-08-29',
    totalVisits: 3,
    treatment: 'Crown & Bridge',
    insuranceProvider: 'Tawuniya Silver',
  },
  {
    id: 'pat-010',
    fullName: 'Tariq Al-Fahad',
    name: 'Tariq Al-Fahad',
    phone: '+966-54-3210987',
    email: 'tariq.fahad@example.com',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    status: 'Inactive',
    dateOfBirth: '1975-05-19',
    gender: 'Male',
    medicalHistory: 'Emergency root canal completed. Missed subsequent crown consultation.',
    lastVisit: '2026-07-12',
    totalVisits: 2,
    treatment: 'Root Canal',
    insuranceProvider: 'Bupa Dental Silver',
  },
  {
    id: 'pat-011',
    fullName: 'Hana Yousef',
    name: 'Hana Yousef',
    phone: '+962-79-8765432',
    email: 'hana.yousef@example.com',
    clinicId: ORG_001_CLINICS.CLIFTON,
    orgId: ORG_001_ID,
    status: 'Active',
    dateOfBirth: '1990-10-08',
    gender: 'Female',
    medicalHistory: 'Surgical wisdom teeth extraction recovery. Sutures removed smoothly.',
    lastVisit: '2026-08-22',
    totalVisits: 5,
    treatment: 'Wisdom Teeth Extraction',
    insuranceProvider: 'EFU General Insurance',
  },
  {
    id: 'pat-012',
    fullName: 'Samir Boutros',
    name: 'Samir Boutros',
    phone: '+20-12-9876543',
    email: 'samir.boutros@example.com',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    status: 'Pending',
    dateOfBirth: '1982-02-14',
    gender: 'Male',
    medicalHistory: 'Periodontal deep scaling requested. Mild chronic gingivitis.',
    lastVisit: null,
    totalVisits: 0,
    treatment: 'Comprehensive Hygiene Scan',
    insuranceProvider: 'Self-Pay',
  },
];

// ── 2. LEADS DATA ─────────────────────────────────────────────────────────────
export const SMILE_CARE_LEADS = [
  {
    id: 'lead-001',
    patientName: 'Ahmed Al-Rashidi',
    name: 'Ahmed Al-Rashidi',
    treatment: 'Dental Implant',
    status: 'qualified',
    priority: 'high',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    phone: '+971-50-1234567',
    email: 'ahmed.rashidi@example.com',
    source: 'Google Ads',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'Called — requested preliminary CBCT pricing',
    lastActivityDate: '2026-09-07T08:30:00.000Z',
    createdAt: '2026-08-26T10:00:00.000Z',
  },
  {
    id: 'lead-002',
    patientName: 'Sara Johnson',
    name: 'Sara Johnson',
    treatment: 'Teeth Whitening',
    status: 'new',
    priority: 'medium',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    phone: '+1-555-2345',
    email: 'sara.j@example.com',
    source: 'Instagram',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'Inquiry submitted from summer promotion ad',
    lastActivityDate: '2026-09-07T09:15:00.000Z',
    createdAt: '2026-09-06T14:30:00.000Z',
  },
  {
    id: 'lead-003',
    patientName: 'Mohammed Hassan',
    name: 'Mohammed Hassan',
    treatment: 'Root Canal',
    status: 'contacted',
    priority: 'high',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    phone: '+966-55-9876543',
    email: 'moh.hassan@example.com',
    source: 'Website',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'Left voicemail regarding emergency tooth pain',
    lastActivityDate: '2026-09-06T11:45:00.000Z',
    createdAt: '2026-09-02T16:00:00.000Z',
  },
  {
    id: 'lead-004',
    patientName: 'Fatima Al-Zaidi',
    name: 'Fatima Al-Zaidi',
    treatment: 'Orthodontics',
    status: 'proposal',
    priority: 'medium',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    phone: '+971-55-3456789',
    email: 'fatima.zaidi@example.com',
    source: 'Referral',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'Sent digital 3D aligner treatment proposal PDF',
    lastActivityDate: '2026-09-06T15:20:00.000Z',
    createdAt: '2026-08-30T09:10:00.000Z',
  },
  {
    id: 'lead-005',
    patientName: 'Khalid Mansour',
    name: 'Khalid Mansour',
    treatment: 'Porcelain Veneers',
    status: 'converted',
    priority: 'low',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    phone: '+966-50-7654321',
    email: 'khalid.m@example.com',
    source: 'WhatsApp',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'Deposit paid and shade selection appointment booked',
    lastActivityDate: '2026-09-05T17:00:00.000Z',
    createdAt: '2026-08-23T11:00:00.000Z',
  },
  {
    id: 'lead-006',
    patientName: 'Nour El-Masry',
    name: 'Nour El-Masry',
    treatment: 'Pediatric Dentistry',
    status: 'new',
    priority: 'low',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    phone: '+20-10-1234567',
    email: 'nour.elmasry@example.com',
    source: 'Google Ads',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'New pediatric consultation lead awaiting call',
    lastActivityDate: '2026-09-07T07:10:00.000Z',
    createdAt: '2026-09-07T07:05:00.000Z',
  },
  {
    id: 'lead-007',
    patientName: 'Rania Haddad',
    name: 'Rania Haddad',
    treatment: 'Teeth Whitening',
    status: 'contacted',
    priority: 'medium',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    phone: '+961-70-9876543',
    email: 'rania.haddad@example.com',
    source: 'Instagram',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'WhatsApp confirmation message delivered',
    lastActivityDate: '2026-09-05T13:40:00.000Z',
    createdAt: '2026-09-04T12:00:00.000Z',
  },
  {
    id: 'lead-008',
    patientName: 'Omar Tariq',
    name: 'Omar Tariq',
    treatment: 'Dental Implant',
    status: 'qualified',
    priority: 'high',
    clinicId: ORG_001_CLINICS.GULBERG,
    orgId: ORG_001_ID,
    phone: '+92-300-1234567',
    email: 'omar.tariq@example.com',
    source: 'Google Ads',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'Video consultation completed with surgeon',
    lastActivityDate: '2026-09-04T16:00:00.000Z',
    createdAt: '2026-09-01T10:30:00.000Z',
  },
  {
    id: 'lead-009',
    patientName: 'Lina Khalil',
    name: 'Lina Khalil',
    treatment: 'Invisalign',
    status: 'proposal',
    priority: 'high',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    phone: '+961-71-5432109',
    email: 'lina.khalil@example.com',
    source: 'Referral',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'Financing package options emailed',
    lastActivityDate: '2026-09-04T14:15:00.000Z',
    createdAt: '2026-08-29T15:20:00.000Z',
  },
  {
    id: 'lead-010',
    patientName: 'Tariq Al-Fahad',
    name: 'Tariq Al-Fahad',
    treatment: 'Root Canal',
    status: 'lost',
    priority: 'low',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    phone: '+966-54-3210987',
    email: 'tariq.fahad@example.com',
    source: 'TV Ad',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'No response after 4 outreach attempts',
    lastActivityDate: '2026-09-02T10:00:00.000Z',
    createdAt: '2026-08-18T09:00:00.000Z',
  },
  {
    id: 'lead-011',
    patientName: 'Hana Yousef',
    name: 'Hana Yousef',
    treatment: 'Crown & Bridge',
    status: 'converted',
    priority: 'medium',
    clinicId: ORG_001_CLINICS.CLIFTON,
    orgId: ORG_001_ID,
    phone: '+962-79-8765432',
    email: 'hana.yousef@example.com',
    source: 'Website',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'Treatment plan agreed; initial impression booked',
    lastActivityDate: '2026-09-03T11:30:00.000Z',
    createdAt: '2026-08-27T13:45:00.000Z',
  },
  {
    id: 'lead-012',
    patientName: 'Samir Boutros',
    name: 'Samir Boutros',
    treatment: 'Comprehensive Hygiene Scan',
    status: 'contacted',
    priority: 'low',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    phone: '+20-12-9876543',
    email: 'samir.boutros@example.com',
    source: 'Instagram',
    assignedAgentId: 'user-003',
    assignedAgentName: 'Alex Johnson',
    lastActivity: 'Call scheduled for tomorrow 11:00 AM',
    lastActivityDate: '2026-09-06T18:00:00.000Z',
    createdAt: '2026-09-05T08:00:00.000Z',
  },
];

// ── 3. CALL LOGS DATA ─────────────────────────────────────────────────────────
export const SMILE_CARE_CALLS = [
  {
    id: 'call-001',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Ahmed Al-Rashidi',
    phone: '+971-50-1234567',
    date: '2026-09-07T08:30:00.000Z',
    duration: 215,
    outcome: 'contacted',
    notes: 'Reviewed implant procedure steps and sedation options. Patient is enthusiastic.',
  },
  {
    id: 'call-002',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Sara Johnson',
    phone: '+1-555-2345',
    date: '2026-09-07T09:20:00.000Z',
    duration: 340,
    outcome: 'booked',
    notes: 'Booked in-office whitening session for Thursday 2:00 PM.',
  },
  {
    id: 'call-003',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Mohammed Hassan',
    phone: '+966-55-9876543',
    date: '2026-09-06T11:45:00.000Z',
    duration: 0,
    outcome: 'missed',
    notes: 'Inbound missed call during lunch hour. Priority follow-up required.',
  },
  {
    id: 'call-004',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Fatima Al-Zaidi',
    phone: '+971-55-3456789',
    date: '2026-09-06T15:15:00.000Z',
    duration: 410,
    outcome: 'booked',
    notes: 'Discussed monthly payment plan for clear aligners; appointment set.',
  },
  {
    id: 'call-005',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Khalid Mansour',
    phone: '+966-50-7654321',
    date: '2026-09-05T16:50:00.000Z',
    duration: 180,
    outcome: 'contacted',
    notes: 'Answered lab turnaround time questions for porcelain veneer mockup.',
  },
  {
    id: 'call-006',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Nour El-Masry',
    phone: '+20-10-1234567',
    date: '2026-09-07T07:15:00.000Z',
    duration: 0,
    outcome: 'no-answer',
    notes: 'Outgoing call rang out. Sent automatic WhatsApp reminder.',
  },
  {
    id: 'call-007',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Rania Haddad',
    phone: '+961-70-9876543',
    date: '2026-09-05T13:30:00.000Z',
    duration: 290,
    outcome: 'contacted',
    notes: 'Followed up on shade guide selection results from previous exam.',
  },
  {
    id: 'call-008',
    clinicId: ORG_001_CLINICS.GULBERG,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Omar Tariq',
    phone: '+92-300-1234567',
    date: '2026-09-04T15:50:00.000Z',
    duration: 520,
    outcome: 'booked',
    notes: 'Completed full surgical consultation call; deposit link sent.',
  },
  {
    id: 'call-009',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Lina Khalil',
    phone: '+961-71-5432109',
    date: '2026-09-04T14:00:00.000Z',
    duration: 175,
    outcome: 'contacted',
    notes: 'Explored dental insurance pre-authorization status.',
  },
  {
    id: 'call-010',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Tariq Al-Fahad',
    phone: '+966-54-3210987',
    date: '2026-09-02T09:55:00.000Z',
    duration: 0,
    outcome: 'no-answer',
    notes: 'Fourth attempt; phone switched off.',
  },
  {
    id: 'call-011',
    clinicId: ORG_001_CLINICS.CLIFTON,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Hana Yousef',
    phone: '+962-79-8765432',
    date: '2026-09-03T11:15:00.000Z',
    duration: 380,
    outcome: 'booked',
    notes: 'Confirmed 3-unit bridge preparation appointment.',
  },
  {
    id: 'call-012',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    agentId: 'user-003',
    agentName: 'Alex Johnson',
    leadName: 'Samir Boutros',
    phone: '+20-12-9876543',
    date: '2026-09-06T17:45:00.000Z',
    duration: 160,
    outcome: 'contacted',
    notes: 'Scheduled comprehensive periodontal evaluation call.',
  },
];

// ── 4. TASKS DATA ─────────────────────────────────────────────────────────────
const getTodayStr = () => new Date().toISOString().split('T')[0];
const getDaysOffset = (n) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};

export const SMILE_CARE_TASKS = [
  {
    id: 'task-001',
    title: 'Call Ahmed Al-Rashidi for Implant Consultation',
    type: 'Call',
    taskType: 'Call',
    leadName: 'Ahmed Al-Rashidi',
    leadId: 'lead-001',
    priority: 'High',
    status: 'Pending',
    due_date: getTodayStr(),
    due_time: '10:00',
    dueDate: `${getTodayStr()}T10:00:00`,
    assignee_id: 'user-003',
    assigneeId: 'user-003',
    assignedAgentId: 'user-003',
    clinic_id: ORG_001_CLINICS.DOWNTOWN,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    organization_id: ORG_001_ID,
    orgId: ORG_001_ID,
    completion_notes: '',
  },
  {
    id: 'task-002',
    title: 'Send WhatsApp Follow-up to Sara Johnson',
    type: 'WhatsApp',
    taskType: 'WhatsApp',
    leadName: 'Sara Johnson',
    leadId: 'lead-002',
    priority: 'Normal',
    status: 'In Progress',
    due_date: getTodayStr(),
    due_time: '14:00',
    dueDate: `${getTodayStr()}T14:00:00`,
    assignee_id: 'user-003',
    assigneeId: 'user-003',
    assignedAgentId: 'user-003',
    clinic_id: ORG_001_CLINICS.WEST,
    clinicId: ORG_001_CLINICS.WEST,
    organization_id: ORG_001_ID,
    orgId: ORG_001_ID,
    completion_notes: '',
  },
  {
    id: 'task-003',
    title: 'Review CBCT 3D Scan with Dr. Reyes',
    type: 'Consultation',
    taskType: 'Consultation',
    leadName: 'Mohammed Hassan',
    leadId: 'lead-003',
    priority: 'High',
    status: 'Pending',
    due_date: getTodayStr(),
    due_time: '16:30',
    dueDate: `${getTodayStr()}T16:30:00`,
    assignee_id: 'user-003',
    assigneeId: 'user-003',
    assignedAgentId: 'user-003',
    clinic_id: ORG_001_CLINICS.DOWNTOWN,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    organization_id: ORG_001_ID,
    orgId: ORG_001_ID,
    completion_notes: '',
  },
  {
    id: 'task-004',
    title: 'Send Financing Agreement to Fatima Al-Zaidi',
    type: 'Email',
    taskType: 'Email',
    leadName: 'Fatima Al-Zaidi',
    leadId: 'lead-004',
    priority: 'Normal',
    status: 'Pending',
    due_date: getDaysOffset(2),
    due_time: '11:00',
    dueDate: `${getDaysOffset(2)}T11:00:00`,
    assignee_id: 'user-003',
    assigneeId: 'user-003',
    assignedAgentId: 'user-003',
    clinic_id: ORG_001_CLINICS.WEST,
    clinicId: ORG_001_CLINICS.WEST,
    organization_id: ORG_001_ID,
    orgId: ORG_001_ID,
    completion_notes: '',
  },
  {
    id: 'task-005',
    title: 'Order Custom Ceramic Shading Guide',
    type: 'Follow-up',
    taskType: 'Follow-up',
    leadName: 'Khalid Mansour',
    leadId: 'lead-005',
    priority: 'Normal',
    status: 'Completed',
    due_date: getDaysOffset(-2),
    due_time: '17:00',
    dueDate: `${getDaysOffset(-2)}T17:00:00`,
    assignee_id: 'user-003',
    assigneeId: 'user-003',
    assignedAgentId: 'user-003',
    clinic_id: ORG_001_CLINICS.DOWNTOWN,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    organization_id: ORG_001_ID,
    orgId: ORG_001_ID,
    completion_notes: 'Lab confirmed delivery for Wednesday morning.',
  },
  {
    id: 'task-006',
    title: 'Urgent: Follow-up on Overdue Recall Visit',
    type: 'Call',
    taskType: 'Call',
    leadName: 'Tariq Al-Fahad',
    leadId: 'lead-010',
    priority: 'High',
    status: 'Pending',
    due_date: getDaysOffset(-3),
    due_time: '09:00',
    dueDate: `${getDaysOffset(-3)}T09:00:00`,
    assignee_id: 'user-003',
    assigneeId: 'user-003',
    assignedAgentId: 'user-003',
    clinic_id: ORG_001_CLINICS.WEST,
    clinicId: ORG_001_CLINICS.WEST,
    organization_id: ORG_001_ID,
    orgId: ORG_001_ID,
    completion_notes: '',
  },
  {
    id: 'task-007',
    title: 'Confirm Post-Op Surgical Recovery Check',
    type: 'Call',
    taskType: 'Call',
    leadName: 'Omar Tariq',
    leadId: 'lead-008',
    priority: 'Normal',
    status: 'Pending',
    due_date: getDaysOffset(3),
    due_time: '12:00',
    dueDate: `${getDaysOffset(3)}T12:00:00`,
    assignee_id: 'user-003',
    assigneeId: 'user-003',
    assignedAgentId: 'user-003',
    clinic_id: ORG_001_CLINICS.GULBERG,
    clinicId: ORG_001_CLINICS.GULBERG,
    organization_id: ORG_001_ID,
    orgId: ORG_001_ID,
    completion_notes: '',
  },
  {
    id: 'task-008',
    title: 'Verify Dental Insurance Pre-Authorization',
    type: 'Email',
    taskType: 'Email',
    leadName: 'Lina Khalil',
    leadId: 'lead-009',
    priority: 'Normal',
    status: 'Completed',
    due_date: getDaysOffset(-1),
    due_time: '15:00',
    dueDate: `${getDaysOffset(-1)}T15:00:00`,
    assignee_id: 'user-003',
    assigneeId: 'user-003',
    assignedAgentId: 'user-003',
    clinic_id: ORG_001_CLINICS.DOWNTOWN,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    organization_id: ORG_001_ID,
    orgId: ORG_001_ID,
    completion_notes: 'Coverage approved at 80% for crown restoration.',
  },
];

// ── 5. PAYMENTS & TRANSACTIONS DATA ───────────────────────────────────────────
export const SMILE_CARE_PAYMENTS = [
  {
    id: 'tx-101',
    patientName: 'Ahmed Al-Rashidi',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    date: '2026-09-07T09:30:00.000Z',
    month: '2026-09',
    revenue: 2800,
    method: 'Credit Card',
    status: 'Paid',
    notes: 'Implant Placement Phase 1 (Titanium Fixture)',
  },
  {
    id: 'tx-102',
    patientName: 'Sara Johnson',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    date: '2026-09-06T15:45:00.000Z',
    month: '2026-09',
    revenue: 450,
    method: 'Credit Card',
    status: 'Paid',
    notes: 'Laser Teeth Whitening Session + Home Kit',
  },
  {
    id: 'tx-103',
    patientName: 'Mohammed Hassan',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    date: '2026-09-05T12:15:00.000Z',
    month: '2026-09',
    revenue: 1200,
    method: 'Insurance',
    status: 'Paid',
    notes: 'Molar Endodontic Therapy (Root Canal)',
  },
  {
    id: 'tx-104',
    patientName: 'Fatima Al-Zaidi',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    date: '2026-09-04T16:20:00.000Z',
    month: '2026-09',
    revenue: 1850,
    method: 'Bank Transfer',
    status: 'Paid',
    notes: 'Clear Aligners Tranche #2 Payment',
  },
  {
    id: 'tx-105',
    patientName: 'Khalid Mansour',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    date: '2026-09-03T11:00:00.000Z',
    month: '2026-09',
    revenue: 4200,
    method: 'Credit Card',
    status: 'Paid',
    notes: 'Porcelain Veneers (Upper 6 Units Deposit)',
  },
  {
    id: 'tx-106',
    patientName: 'Nour El-Masry',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    date: '2026-09-02T14:30:00.000Z',
    month: '2026-09',
    revenue: 220,
    method: 'Cash',
    status: 'Paid',
    notes: 'Pediatric Comprehensive Exam & Fluoride Varnish',
  },
  {
    id: 'tx-107',
    patientName: 'Rania Haddad',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    date: '2026-09-01T10:15:00.000Z',
    month: '2026-09',
    revenue: 650,
    method: 'Credit Card',
    status: 'Paid',
    notes: 'Custom Night Guard & Occlusal Adjustment',
  },
  {
    id: 'tx-108',
    patientName: 'Omar Tariq',
    clinicId: ORG_001_CLINICS.GULBERG,
    orgId: ORG_001_ID,
    date: '2026-08-29T16:40:00.000Z',
    month: '2026-08',
    revenue: 2400,
    method: 'Bank Transfer',
    status: 'Paid',
    notes: 'Surgical Implant Stage 2 Abutment Fitting',
  },
  {
    id: 'tx-109',
    patientName: 'Lina Khalil',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    date: '2026-08-27T13:20:00.000Z',
    month: '2026-08',
    revenue: 980,
    method: 'Insurance',
    status: 'Paid',
    notes: 'Zirconia Crown Placement Lower Molar',
  },
  {
    id: 'tx-110',
    patientName: 'Hana Yousef',
    clinicId: ORG_001_CLINICS.CLIFTON,
    orgId: ORG_001_ID,
    date: '2026-08-25T15:00:00.000Z',
    month: '2026-08',
    revenue: 1600,
    method: 'Credit Card',
    status: 'Paid',
    notes: '3-Unit Ceramic Bridge Delivery',
  },
  {
    id: 'tx-111',
    patientName: 'Samir Boutros',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    date: '2026-08-22T09:40:00.000Z',
    month: '2026-08',
    revenue: 350,
    method: 'Cash',
    status: 'Paid',
    notes: 'Full Mouth Ultrasonic Scaling & Polish',
  },
  {
    id: 'tx-112',
    patientName: 'Ahmed Al-Rashidi',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    date: '2026-08-20T11:10:00.000Z',
    month: '2026-08',
    revenue: 850,
    method: 'Insurance',
    status: 'Pending',
    notes: 'Bone Grafting Material Co-pay (Pending Ins Claim)',
  },
  // Aggregate Monthly Records for RevenueView comparisons
  {
    id: 'rev-m01',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    month: '2026-08',
    revenue: 28400,
    conversions: 14,
    leadsAssigned: 32,
    conversionRate: 43.8,
  },
  {
    id: 'rev-m02',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    month: '2026-08',
    revenue: 19800,
    conversions: 11,
    leadsAssigned: 26,
    conversionRate: 42.3,
  },
  {
    id: 'rev-m03',
    clinicId: ORG_001_CLINICS.GULBERG,
    orgId: ORG_001_ID,
    month: '2026-08',
    revenue: 14200,
    conversions: 8,
    leadsAssigned: 20,
    conversionRate: 40.0,
  },
  {
    id: 'rev-m04',
    clinicId: ORG_001_CLINICS.CLIFTON,
    orgId: ORG_001_ID,
    month: '2026-08',
    revenue: 12500,
    conversions: 7,
    leadsAssigned: 18,
    conversionRate: 38.9,
  },
  {
    id: 'rev-m05',
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    orgId: ORG_001_ID,
    month: '2026-07',
    revenue: 26200,
    conversions: 12,
    leadsAssigned: 30,
    conversionRate: 40.0,
  },
  {
    id: 'rev-m06',
    clinicId: ORG_001_CLINICS.WEST,
    orgId: ORG_001_ID,
    month: '2026-07',
    revenue: 18100,
    conversions: 9,
    leadsAssigned: 24,
    conversionRate: 37.5,
  },
];

// ── 6. SMILE CARE GROUP STAFF USERS ───────────────────────────────────────────
export const SMILE_CARE_USERS = [
  {
    id: 'user-001',
    name: 'Dr. John Doe',
    fullName: 'Dr. John Doe',
    email: 'orgadmin@test.com',
    role: 'org_admin',
    organizationId: ORG_001_ID,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    clinicIds: [ORG_001_CLINICS.DOWNTOWN, ORG_001_CLINICS.WEST, ORG_001_CLINICS.GULBERG, ORG_001_CLINICS.CLIFTON],
    status: 'active',
    invitedAt: null,
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: '2026-01-10T00:00:00.000Z',
    lastLoginAt: '2026-09-07T08:30:00.000Z',
  },
  {
    id: 'user-002',
    name: 'Dr. Sarah Khan',
    fullName: 'Dr. Sarah Khan',
    email: 'manager@test.com',
    role: 'clinic_manager',
    organizationId: ORG_001_ID,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    clinicIds: [ORG_001_CLINICS.DOWNTOWN],
    status: 'active',
    invitedAt: null,
    createdAt: '2026-01-12T00:00:00.000Z',
    updatedAt: '2026-01-12T00:00:00.000Z',
    lastLoginAt: '2026-09-07T09:00:00.000Z',
  },
  {
    id: 'user-002b',
    name: 'Dr. Marcus Vance',
    fullName: 'Dr. Marcus Vance',
    email: 'm.vance@smilecare.com',
    role: 'clinic_manager',
    organizationId: ORG_001_ID,
    clinicId: ORG_001_CLINICS.WEST,
    clinicIds: [ORG_001_CLINICS.WEST],
    status: 'active',
    invitedAt: null,
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-02-01T00:00:00.000Z',
    lastLoginAt: '2026-09-06T17:20:00.000Z',
  },
  {
    id: 'user-003',
    name: 'Alex Johnson',
    fullName: 'Alex Johnson',
    email: 'agent@test.com',
    role: 'agent',
    organizationId: ORG_001_ID,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    clinicIds: [ORG_001_CLINICS.DOWNTOWN, ORG_001_CLINICS.WEST],
    status: 'active',
    invitedAt: null,
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
    lastLoginAt: '2026-09-07T09:15:00.000Z',
  },
  {
    id: 'user-004',
    name: 'Maya Al-Mansoor',
    fullName: 'Maya Al-Mansoor',
    email: 'receptionist@test.com',
    role: 'receptionist',
    organizationId: ORG_001_ID,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    clinicIds: [ORG_001_CLINICS.DOWNTOWN],
    status: 'active',
    invitedAt: null,
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-01-20T00:00:00.000Z',
    lastLoginAt: '2026-09-07T08:00:00.000Z',
  },
  {
    id: 'user-004b',
    name: 'Fatima Zahra',
    fullName: 'Fatima Zahra',
    email: 'fatima.z@smilecare.com',
    role: 'receptionist',
    organizationId: ORG_001_ID,
    clinicId: ORG_001_CLINICS.WEST,
    clinicIds: [ORG_001_CLINICS.WEST],
    status: 'active',
    invitedAt: null,
    createdAt: '2026-02-10T00:00:00.000Z',
    updatedAt: '2026-02-10T00:00:00.000Z',
    lastLoginAt: '2026-09-07T08:15:00.000Z',
  },
  {
    id: 'user-005',
    name: 'Elena Rostova',
    fullName: 'Elena Rostova',
    email: 'finance@test.com',
    role: 'finance',
    organizationId: ORG_001_ID,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    clinicIds: [ORG_001_CLINICS.DOWNTOWN, ORG_001_CLINICS.WEST],
    status: 'active',
    invitedAt: null,
    createdAt: '2026-02-05T00:00:00.000Z',
    updatedAt: '2026-02-05T00:00:00.000Z',
    lastLoginAt: '2026-09-06T16:00:00.000Z',
  },
  {
    id: 'user-006',
    name: 'Zainab Qureshi',
    fullName: 'Zainab Qureshi',
    email: 'auditor@test.com',
    role: 'auditor',
    organizationId: ORG_001_ID,
    clinicId: ORG_001_CLINICS.DOWNTOWN,
    clinicIds: [ORG_001_CLINICS.DOWNTOWN],
    status: 'active',
    invitedAt: null,
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: '2026-02-15T00:00:00.000Z',
    lastLoginAt: '2026-09-05T14:30:00.000Z',
  },
];
