/**
 * PIPELINE CONSTANTS & CONFIGURATIONS
 */

export const PIPELINE_STATUSES = [
  { id: 'all', label: 'All Statuses' },
  { id: 'new', label: 'New Lead', color: 'blue' },
  { id: 'contacted', label: 'Contacted', color: 'amber' },
  { id: 'booked', label: 'Appointment Booked', color: 'purple' },
  { id: 'attended', label: 'Attended', color: 'purple' },
  { id: 'converted', label: 'Converted', color: 'success' },
  { id: 'lost', label: 'Lost', color: 'error' },
];

export const PIPELINE_STAGES = [
  { id: 'new', label: 'New Inquiries', color: 'blue', headerColor: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'contacted', label: 'Contacted & Engaged', color: 'amber', headerColor: 'bg-amber-50 text-amber-700 border-amber-200' },
  { id: 'booked', label: 'Appointment Booked', color: 'purple', headerColor: 'bg-purple-50 text-purple-700 border-purple-200' },
  { id: 'attended', label: 'Consultation Attended', color: 'purple', headerColor: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { id: 'converted', label: 'Treatment Accepted', color: 'success', headerColor: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'lost', label: 'Closed / Lost', color: 'error', headerColor: 'bg-rose-50 text-rose-700 border-rose-200' },
];

export const LEAD_SOURCES = [
  { id: 'all', label: 'All Sources' },
  { id: 'Google Ads', label: 'Google Ads' },
  { id: 'Website', label: 'Website Form' },
  { id: 'Instagram', label: 'Meta (Instagram)' },
  { id: 'Quiz', label: 'Smile Assessment Quiz' },
  { id: 'WhatsApp', label: 'WhatsApp Bot' },
  { id: 'Referral', label: 'Patient Referral' },
];

export const TREATMENTS_LIST = [
  'Dental Implant',
  'Teeth Whitening',
  'Invisalign',
  'Root Canal',
  'Orthodontics',
  'Veneers',
  'Dental Cleaning',
  'Crown & Bridge',
  'Pediatric Dentistry',
];

export const AGENTS_LIST = [
  { id: 'agent-001', name: 'Aisha Patel (Senior Agent)' },
  { id: 'agent-002', name: 'Ali Raza (Conversion Specialist)' },
  { id: 'agent-003', name: 'Jessica Taylor (Invisalign Lead)' },
  { id: 'agent-004', name: 'Emma Watson (VIP Care)' },
];

export const INITIAL_DEMO_LEADS = [
  {
    id: 'lead-101',
    patientName: 'Ahmed Al-Rashidi',
    phone: '+971-50-1234567',
    email: 'ahmed@example.com',
    clinicId: 'clinic-001',
    clinicName: 'Downtown Dental Excellence',
    orgId: 'org-001',
    orgName: 'Smile Care Group',
    treatment: 'Dental Implant',
    status: 'booked',
    priority: 'high',
    aiScore: 94,
    source: 'Google Ads',
    utmCampaign: 'Implant_Search_Tier1',
    utmMedium: 'cpc',
    assignedAgentId: 'agent-001',
    assignedAgentName: 'Aisha Patel',
    createdAt: '2026-08-18',
  },
  {
    id: 'lead-102',
    patientName: 'Sara Johnson',
    phone: '+1-555-2345',
    email: 'sara@example.com',
    clinicId: 'clinic-002',
    clinicName: 'Westside Dental Clinic',
    orgId: 'org-001',
    orgName: 'Smile Care Group',
    treatment: 'Teeth Whitening',
    status: 'new',
    priority: 'medium',
    aiScore: 68,
    source: 'Instagram',
    utmCampaign: 'Summer_Smile_Promo',
    utmMedium: 'social',
    assignedAgentId: null,
    assignedAgentName: null,
    createdAt: '2026-08-19',
  },
  {
    id: 'lead-103',
    patientName: 'Mohammed Hassan',
    phone: '+966-55-9876543',
    email: 'moh@example.com',
    clinicId: 'clinic-010',
    clinicName: 'Manhattan Smile Hub',
    orgId: 'org-004',
    orgName: 'Apex Dental Group',
    treatment: 'Root Canal',
    status: 'contacted',
    priority: 'high',
    aiScore: 89,
    source: 'Website',
    utmCampaign: 'Emergency_Dentistry_Geo',
    utmMedium: 'organic',
    assignedAgentId: 'agent-002',
    assignedAgentName: 'Ali Raza',
    createdAt: '2026-08-17',
  },
  {
    id: 'lead-104',
    patientName: 'Fatima Al-Zaidi',
    phone: '+971-55-3456789',
    email: 'fatima@example.com',
    clinicId: 'clinic-005',
    clinicName: 'Marina Branch',
    orgId: 'org-002',
    orgName: 'Dental Plus',
    treatment: 'Orthodontics',
    status: 'attended',
    priority: 'medium',
    aiScore: 78,
    source: 'Referral',
    utmCampaign: 'Friend_Family_Share',
    utmMedium: 'referral',
    assignedAgentId: 'agent-003',
    assignedAgentName: 'Jessica Taylor',
    createdAt: '2026-08-15',
  },
  {
    id: 'lead-105',
    patientName: 'Khalid Mansour',
    phone: '+966-50-7654321',
    email: 'khalid@example.com',
    clinicId: 'clinic-001',
    clinicName: 'Downtown Dental Excellence',
    orgId: 'org-001',
    orgName: 'Smile Care Group',
    treatment: 'Veneers',
    status: 'converted',
    priority: 'high',
    aiScore: 98,
    source: 'Quiz',
    utmCampaign: 'Cosmetic_Smile_Quiz_V2',
    utmMedium: 'quiz',
    assignedAgentId: 'agent-001',
    assignedAgentName: 'Aisha Patel',
    createdAt: '2026-08-12',
  },
  {
    id: 'lead-106',
    patientName: 'Nour El-Masry',
    phone: '+20-10-1234567',
    email: 'nour@example.com',
    clinicId: 'clinic-011',
    clinicName: 'Brooklyn Orthodontics',
    orgId: 'org-004',
    orgName: 'Apex Dental Group',
    treatment: 'Invisalign',
    status: 'new',
    priority: 'low',
    aiScore: 45,
    source: 'WhatsApp',
    utmCampaign: 'Inbound_Chatbot',
    utmMedium: 'direct',
    assignedAgentId: null,
    assignedAgentName: null,
    createdAt: '2026-08-20',
  },
  {
    id: 'lead-107',
    patientName: 'Rania Haddad',
    phone: '+961-70-9876543',
    email: 'rania@example.com',
    clinicId: 'clinic-013',
    clinicName: 'Olaya Dental Center',
    orgId: 'org-005',
    orgName: 'Saudi Smiles',
    treatment: 'Teeth Whitening',
    status: 'contacted',
    priority: 'medium',
    aiScore: 72,
    source: 'Instagram',
    utmCampaign: 'VIP_Whitening_Reel',
    utmMedium: 'social',
    assignedAgentId: 'agent-004',
    assignedAgentName: 'Emma Watson',
    createdAt: '2026-08-19',
  },
  {
    id: 'lead-108',
    patientName: 'Omar Tariq',
    phone: '+92-300-1234567',
    email: 'omar@example.com',
    clinicId: 'clinic-006',
    clinicName: 'Jumeirah Care',
    orgId: 'org-002',
    orgName: 'Dental Plus',
    treatment: 'Dental Implant',
    status: 'booked',
    priority: 'high',
    aiScore: 92,
    source: 'Google Ads',
    utmCampaign: 'Dubai_Expat_Implants',
    utmMedium: 'cpc',
    assignedAgentId: 'agent-002',
    assignedAgentName: 'Ali Raza',
    createdAt: '2026-08-16',
  },
];

export const formatCurrency = (val) => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(val || 0);
};

export const safePct = (numerator, denominator) => {
  const n = Number(numerator) || 0;
  const d = Number(denominator) || 0;
  if (d <= 0) return '0%';
  return `${((n / d) * 100).toFixed(1)}%`;
};
