export const rawActivityFeed = [
  {
    id: 'a1',
    actor: 'AI Voice Bot #3',
    action: 'Booked Full-Mouth Dental Implant Consultation',
    target: 'Patient: Marcus Vance',
    clinic: 'Downtown Dental',
    orgId: 'apex',
    timestamp: '5 mins ago',
    status: 'success',
  },
  {
    id: 'a2',
    actor: 'Dr. Sarah Lin',
    action: 'Updated Monthly Target to $150k',
    target: 'Clinic: Apex Orthodontics',
    clinic: 'Apex Smiles',
    orgId: 'apex',
    timestamp: '22 mins ago',
    status: 'info',
  },
  {
    id: 'a3',
    actor: 'AI Guardrail System',
    action: 'Flagged High Token Usage (14.2k tokens)',
    target: 'Prompt: Invisalign Assistant v2.1',
    clinic: 'Westside Branch',
    orgId: 'smilecare',
    timestamp: '45 mins ago',
    status: 'warning',
  },
  {
    id: 'a4',
    actor: 'Finance Bot',
    action: 'Processed Deposit Payment ($1,500.00)',
    target: 'Invoice #INV-9041',
    clinic: 'Metro Cosmetic',
    orgId: 'smilecare',
    timestamp: '1 hour ago',
    status: 'success',
  },
];
