export const kpiOverviewData = {
  timeRanges: ['Today', '7 Days', '30 Days', 'This Quarter', 'YTD'],
  metrics: [
    {
      id: 'total_leads',
      title: 'Total Leads',
      value: '1,428',
      change: '+14.2%',
      isPositive: true,
      period: 'vs last month',
      category: 'Leads',
      sparkline: [45, 52, 58, 65, 72, 68, 84, 95, 110, 125, 138, 142],
    },
    {
      id: 'contact_rate',
      title: 'Contact Rate',
      value: '88.4%',
      change: '+3.1%',
      isPositive: true,
      period: 'vs last month',
      category: 'Conversion',
      sparkline: [75, 78, 80, 82, 81, 85, 84, 86, 87, 88, 88, 88.4],
    },
    {
      id: 'booking_rate',
      title: 'Booking Rate',
      value: '42.6%',
      change: '+5.8%',
      isPositive: true,
      period: 'vs last month',
      category: 'Conversion',
      sparkline: [30, 32, 34, 35, 38, 36, 39, 40, 41, 41.5, 42, 42.6],
    },
    {
      id: 'attendance_rate',
      title: 'Attendance Rate',
      value: '91.2%',
      change: '+1.5%',
      isPositive: true,
      period: 'vs last month',
      category: 'Operations',
      sparkline: [88, 89, 88.5, 90, 89.8, 90.5, 91, 90.8, 91.2, 91, 91.2, 91.2],
    },
    {
      id: 'no_show_rate',
      title: 'No Show Rate',
      value: '8.8%',
      change: '-1.5%',
      isPositive: true, // Lower no show rate is positive
      period: 'vs last month',
      category: 'Operations',
      sparkline: [12, 11, 11.5, 10, 10.2, 9.5, 9, 9.2, 8.8, 9, 8.8, 8.8],
    },
    {
      id: 'revenue',
      title: 'Total Revenue',
      value: '$342,850',
      change: '+18.6%',
      isPositive: true,
      period: 'vs last month',
      category: 'Financial',
      sparkline: [210, 225, 240, 255, 270, 260, 295, 310, 325, 330, 338, 342.8],
    },
    {
      id: 'avg_treatment_val',
      title: 'Avg Treatment Value',
      value: '$2,450',
      change: '+4.2%',
      isPositive: true,
      period: 'vs last month',
      category: 'Financial',
      sparkline: [2100, 2150, 2200, 2250, 2300, 2280, 2350, 2390, 2410, 2430, 2440, 2450],
    },
    {
      id: 'active_clinics',
      title: 'Active Clinics',
      value: '4 Branches',
      change: '+1 Clinic',
      isPositive: true,
      period: 'vs last quarter',
      category: 'Scale',
      sparkline: [3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4],
    },
    {
      id: 'active_users',
      title: 'Active System Users',
      value: '38 Staff',
      change: '+6 Users',
      isPositive: true,
      period: 'vs last month',
      category: 'Scale',
      sparkline: [28, 29, 30, 30, 32, 33, 34, 35, 36, 37, 38, 38],
    },
  ],
  recentActivities: [
    {
      id: 'a1',
      actor: 'AI Voice Bot #3',
      action: 'Booked Full-Mouth Dental Implant Consultation',
      target: 'Patient: Marcus Vance',
      clinic: 'Downtown Dental',
      timestamp: '5 mins ago',
      status: 'success',
    },
    {
      id: 'a2',
      actor: 'Dr. Sarah Lin',
      action: 'Updated Monthly Target to $150k',
      target: 'Clinic: Apex Orthodontics',
      clinic: 'Apex Smiles',
      timestamp: '22 mins ago',
      status: 'info',
    },
    {
      id: 'a3',
      actor: 'AI Guardrail System',
      action: 'Flagged High Token Usage (14.2k tokens)',
      target: 'Prompt: Invisalign Assistant v2.1',
      clinic: 'Westside Branch',
      timestamp: '45 mins ago',
      status: 'warning',
    },
    {
      id: 'a4',
      actor: 'Finance Bot',
      action: 'Processed Deposit Payment ($1,500.00)',
      target: 'Invoice #INV-9041',
      clinic: 'Downtown Dental',
      timestamp: '1 hour ago',
      status: 'success',
    },
  ],
  aiHealthStatus: {
    status: 'Optimal',
    latencyMs: 340,
    successRate: '99.4%',
    activeAgents: 12,
    todayCalls: 1842,
  },
};
