export const ORGANIZATIONS = [
  {
    id: 'all',
    name: 'All Organizations (Global Scope)',
    shortName: 'Global Scope',
    badgeText: 'Global Scope',
    isGlobal: true,
    logoText: 'GA',
    clinicsCount: 15,
  },
  {
    id: 'org-001',
    name: 'Smile Care Group',
    shortName: 'Smile Care',
    badgeText: 'Smile Care Group',
    isGlobal: false,
    logoText: 'SC',
    logoColor: 'from-teal-600 to-emerald-600',
    clinicsCount: 4,
    assignedClinicIds: ['clinic-downtown', 'clinic-west', 'clinic-003', 'clinic-004'],
  },
  {
    id: 'org-002',
    name: 'Dental Plus',
    shortName: 'Dental Plus',
    badgeText: 'Dental Plus',
    isGlobal: false,
    logoText: 'DP',
    logoColor: 'from-blue-600 to-cyan-600',
    clinicsCount: 3,
    assignedClinicIds: ['clinic-005', 'clinic-006', 'clinic-007'],
  },
  {
    id: 'org-003',
    name: 'Bright Dental',
    shortName: 'Bright Dental',
    badgeText: 'Bright Dental',
    isGlobal: false,
    logoText: 'BD',
    logoColor: 'from-amber-600 to-orange-600',
    clinicsCount: 2,
    assignedClinicIds: ['clinic-008', 'clinic-009'],
  },
  {
    id: 'org-004',
    name: 'Apex Dental Group',
    shortName: 'Apex Dental',
    badgeText: 'Apex Dental Group',
    isGlobal: false,
    logoText: 'AD',
    logoColor: 'from-purple-600 to-indigo-600',
    clinicsCount: 3,
    assignedClinicIds: ['clinic-central', 'clinic-011', 'clinic-east'],
  },
  {
    id: 'org-005',
    name: 'Saudi Smiles',
    shortName: 'Saudi Smiles',
    badgeText: 'Saudi Smiles',
    isGlobal: false,
    logoText: 'SS',
    logoColor: 'from-emerald-600 to-green-600',
    clinicsCount: 2,
    assignedClinicIds: ['clinic-013', 'clinic-014'],
  },
  {
    id: 'org-006',
    name: 'Crown & Care Dental',
    shortName: 'Crown & Care',
    badgeText: 'Crown & Care Dental',
    isGlobal: false,
    logoText: 'CC',
    logoColor: 'from-rose-600 to-pink-600',
    clinicsCount: 1,
    assignedClinicIds: ['clinic-015'],
  },
];
